export default {
  "_context": "Сайт промокодов для неавторизованного трафика. Сейчас на стороне подрядчика. Base = забрать сайт на органике без зарплат и рекламы. Stretch = Base + доп. RnD + реклама с отдельной воронкой.",
  "_traffic_note": "База: 250 000 органических визитов/мес.",
  "_seo_note": "После переезда с домена подрядчика на сайт внутри Т органика падает до 80% и за 6 мес. линейно возвращается к 100% исходного. Реклама и статус-кво не проседают.",
  "_funnel_note": "Из визитов 44% жмут «Активировать»; из них 4% доходят до целевого действия; партнёр оплачивает 100% одобренных. Итого оплачиваемая конверсия ≈ 1,76% трафика.",
  "_arpu_note": "ARPU 150 ₽ — выплата за оплаченную активацию. Меняется в панели.",
  "_cards_note": "Выручка карт = трафик × доля оформивших × LTV. LTV Black 3 000 ₽ и Platinum 25 000 ₽ — оценочно, lifetime в месяц оформления. Доли по умолчанию 0%, чтобы не раздувать текущую промо-базу. Доля подрядчика на LTV карт не режется.",
  "num_months": 24,
  "rnd_months": 3,
  "traffic_month": 250000,
  "seo_dip_enabled": true,
  "seo_dip_floor_pct": 80.0,
  "seo_recovery_months": 6,
  "conversion_pct": 44.0,
  "approved_activation_share_pct": 4.0,
  "paid_partner_share_pct": 100.0,
  "arpu": 150.0,
  "contractor_share_pct": 30.0,
  "contractor_share_rnd": 30.0,
  "contractor_share_ops": 0.0,
  "contractor_share_status_quo": 30.0,
  "dev_cost_month": 1800000,
  "dev_cost_rnd": 1800000,
  "dev_cost_ops": 0,
  "dev_cost_status_quo": 0,
  "card_black_enabled": true,
  "black_share_pct": 0.0,
  "black_ltv": 3000.0,
  "card_platinum_enabled": true,
  "platinum_share_pct": 0.0,
  "platinum_ltv": 25000.0,
  "team_headcount_rnd": 0,
  "team_avg_salary_rnd": 250000,
  "team_headcount_ops": 0,
  "team_avg_salary_ops": 200000,
  "salaries_rnd": 0,
  "salaries_ops": 0,
  "salaries_status_quo": 0,
  "support_rnd": 20000,
  "support_ops": 60000,
  "support_status_quo": 20000,
  "own_traffic_lift_pct": 0.0,
  "own_conversion_lift_pct": 0.0,
  "own_approved_share_lift_pct": 0.0,
  "own_paid_share_lift_pct": 0.0,
  "own_arpu_lift_pct": 0.0,
  "ads_enabled": true,
  "ads_start_month": 5,
  "ads_end_month": 0,
  "ads_traffic_month": 0,
  "ads_cost_month": 0,
  "conversion_pct_ads": 5.0,
  "approved_activation_share_pct_ads": 100.0,
  "paid_partner_share_pct_ads": 8.0,
  "extra_rnd": [
    {
      "name": "Продуктовый RnD (атрибуция / персонализация)",
      "start_month": 5,
      "duration_months": 6,
      "headcount": 3,
      "avg_salary": 280000,
      "traffic_lift_pct": 15,
      "conversion_lift_pct": 10,
      "approved_lift_pct": 0,
      "paid_lift_pct": 40,
      "arpu_lift_pct": 0,
      "extra_revenue_month": 0
    }
  ],
  "variable_costs": [
    {
      "name": "Хостинг и CDN",
      "kind": "fixed",
      "rnd": 0,
      "ops": 40000,
      "status_quo": 0
    },
    {
      "name": "SEO / контент",
      "kind": "fixed",
      "rnd": 0,
      "ops": 30000,
      "status_quo": 0
    },
    {
      "name": "Атрибуция / антифрод",
      "kind": "per_paid_activation",
      "rnd": 0,
      "ops": 8,
      "status_quo": 0
    }
  ]
};
