export default {
  "_context": "Сайт промокодов для неавторизованного трафика. Сейчас на стороне подрядчика. Base = забрать сайт на органике без зарплат и рекламы. Stretch = Base + доп. RnD + T-ID + onsite eCPM + банк. продукты. Pess = тот же Base с чуть худшими сроками и SEO.",
  "_traffic_note": "База: 250 000 органических визитов/мес.",
  "_seo_note": "После переезда с домена подрядчика на сайт внутри Т органика падает до 80% и за 6 мес. линейно возвращается к seo_final_pct (Base/Stretch = 100%). Реклама и статус-кво не проседают.",
  "_funnel_note": "Из визитов 44% жмут «Активировать»; из них 4% доходят до целевого действия; партнёр оплачивает 100% одобренных. Итого оплачиваемая конверсия ≈ 1,76% трафика.",
  "_arpu_note": "ARPU 150 ₽ — выплата за оплаченную активацию. Меняется в панели.",
  "_cards_note": "Base/Pess: выручка карт = трафик × доля × LTV (доли по умолчанию 0%). Stretch: банковская воронка show × util × incrementality × LTV. Доля подрядчика на LTV карт и onsite eCPM не режется.",
  "num_months": 24,
  "rnd_months": 3,
  "traffic_month": 250000,
  "seo_dip_enabled": true,
  "seo_dip_floor_pct": 80.0,
  "seo_recovery_months": 6,
  "seo_final_pct": 100.0,
  "seo_share_pct": 100.0,
  "traffic_trend_pct": 0.0,
  "coverage_start_pct": 100.0,
  "coverage_target_pct": 100.0,
  "coverage_ramp_months": 0,
  "mon_start_pct": 100.0,
  "mon_target_pct": 100.0,
  "mon_ramp_months": 0,
  "transition_cost": 0,
  "conversion_pct": 44.0,
  "approved_activation_share_pct": 4.0,
  "paid_partner_share_pct": 100.0,
  "arpu": 150.0,
  "contractor_share_pct": 30.0,
  "contractor_share_rnd": 30.0,
  "contractor_share_ops": 0.0,
  "contractor_share_status_quo": 30.0,
  "dev_cost_month": 1800000,
  "dev_cost_rnd": 1800000,
  "dev_cost_ops": 0,
  "dev_cost_status_quo": 0,
  "card_black_enabled": true,
  "black_share_pct": 0.0,
  "black_ltv": 3000.0,
  "card_platinum_enabled": true,
  "platinum_share_pct": 0.0,
  "platinum_ltv": 25000.0,
  "team_headcount_rnd": 0,
  "team_avg_salary_rnd": 250000,
  "team_headcount_ops": 0,
  "team_avg_salary_ops": 200000,
  "salaries_rnd": 0,
  "salaries_ops": 0,
  "salaries_status_quo": 0,
  "support_rnd": 20000,
  "support_ops": 60000,
  "support_status_quo": 20000,
  "own_traffic_lift_pct": 0.0,
  "own_conversion_lift_pct": 0.0,
  "own_approved_share_lift_pct": 0.0,
  "own_paid_share_lift_pct": 0.0,
  "own_arpu_lift_pct": 0.0,
  "tid_enabled": true,
  "tid_launch": 4,
  "tid_ramp_months": 6,
  "tid_auth_share_pct": 25.0,
  "tid_repeat_lift_pct": 15.0,
  "tid_cpa_lift_pct": 10.0,
  "tid_card_lift_pct": 10.0,
  "onsite_ads_enabled": true,
  "onsite_ad_launch": 4,
  "onsite_ad_impressions": 2,
  "onsite_ad_fill_pct": 60.0,
  "onsite_ad_ecpm": 300.0,
  "bank_enabled": true,
  "bank_launch": 5,
  "bank_ramp_months": 6,
  "debit_show_pct": 10.0,
  "debit_util_pct": 0.5,
  "debit_inc_pct": 50.0,
  "credit_show_pct": 10.0,
  "credit_util_pct": 0.2,
  "credit_inc_pct": 50.0,
  "stretch_extra_traffic": 0,
  "distribution_cost": 0,
  "distribution_launch": 7,
  "ads_enabled": true,
  "ads_start_month": 5,
  "ads_end_month": 0,
  "ads_traffic_month": 0,
  "ads_cost_month": 0,
  "conversion_pct_ads": 5.0,
  "approved_activation_share_pct_ads": 100.0,
  "paid_partner_share_pct_ads": 8.0,
  "extra_rnd": [
    {
      "name": "Продуктовый RnD (атрибуция / персонализация)",
      "start_month": 5,
      "duration_months": 6,
      "headcount": 3,
      "avg_salary": 280000,
      "traffic_lift_pct": 15,
      "conversion_lift_pct": 10,
      "approved_lift_pct": 0,
      "paid_lift_pct": 40,
      "arpu_lift_pct": 0,
      "extra_revenue_month": 0
    }
  ],
  "variable_costs": [
    {
      "name": "Хостинг и CDN",
      "kind": "fixed",
      "rnd": 0,
      "ops": 40000,
      "status_quo": 0
    },
    {
      "name": "SEO / контент",
      "kind": "fixed",
      "rnd": 0,
      "ops": 30000,
      "status_quo": 0
    },
    {
      "name": "Атрибуция / антифрод",
      "kind": "per_paid_activation",
      "rnd": 0,
      "ops": 8,
      "status_quo": 0
    }
  ]
};
